import { CanvasCardItem, Connection, Folder } from '../types/canvas';

export const DEFAULT_FOLDERS: Folder[] = [
  { id: 'python', name: 'Python Learning', iconColor: '#8b5cf6', count: 12 },
  { id: 'django', name: 'Django', iconColor: '#ec4899', count: 5 },
  { id: 'odoo', name: 'Odoo', iconColor: '#f43f5e', count: 3 },
  { id: 'fastapi', name: 'FastAPI', iconColor: '#10b981', count: 8 },
  { id: 'webdev', name: 'Web Development', iconColor: '#06b6d4', count: 14 },
  { id: 'projects', name: 'Projects', iconColor: '#3b82f6', count: 7 },
  { id: 'ideas', name: 'Ideas', iconColor: '#f59e0b', count: 4 },
  { id: 'bookmarks', name: 'Bookmarks', iconColor: '#6366f1', count: 9 },
  { id: 'trash', name: 'Trash', iconColor: '#ef4444', count: 0 },
];

export const INITIAL_CARDS: CanvasCardItem[] = [
  {
    id: 'card-banner',
    type: 'banner',
    x: 40,
    y: 40,
    width: 630,
    title: 'Python Basics',
    accent: 'purple',
    hasGlow: true,
    data: {
      subtitle: 'Learn Python with visual notes, examples and interactive cards',
      tags: [
        { label: 'Beginner', variant: 'green' },
        { label: '12 Cards', variant: 'purple' },
        { label: 'Progress 40%', variant: 'blue' },
      ],
    },
  },
  {
    id: 'card-goal',
    type: 'goal',
    x: 710,
    y: 40,
    width: 380,
    title: 'Learning Goal',
    accent: 'rose',
    hasGlow: false,
    data: {
      goals: [
        { id: 'g1', text: 'Understand Python fundamentals', done: true },
        { id: 'g2', text: 'Practice with examples', done: true },
        { id: 'g3', text: 'Build small projects', done: false },
      ],
    },
  },
  {
    id: 'card-1',
    type: 'concept',
    x: 40,
    y: 220,
    width: 270,
    title: 'What is Python?',
    badgeNumber: 1,
    accent: 'pink',
    hasGlow: true,
    data: {
      content:
        'Python is a high-level, interpreted programming language. It is easy to learn and has a clean syntax.',
      tags: ['Easy to learn', 'Versatile', 'Large community'],
    },
  },
  {
    id: 'card-2',
    type: 'code',
    x: 340,
    y: 220,
    width: 280,
    title: 'Variables',
    badgeNumber: 2,
    accent: 'blue',
    hasGlow: false,
    data: {
      description: 'Variables store data values.',
      language: 'python',
      code: `name = "Deepak"\nage = 25\nis_dev = True\nprint(name, age)`,
      output: 'Deepak 25',
    },
  },
  {
    id: 'card-3',
    type: 'datatypes',
    x: 650,
    y: 220,
    width: 260,
    title: 'Data Types',
    badgeNumber: 3,
    accent: 'emerald',
    hasGlow: false,
    data: {
      description: 'Python has several built-in data types.',
      items: [
        { type: 'int', val: '10', color: 'blue' },
        { type: 'float', val: '10.5', color: 'cyan' },
        { type: 'str', val: '"Hello"', color: 'pink' },
        { type: 'bool', val: 'True', color: 'amber' },
        { type: 'list', val: '[1, 2, 3]', color: 'emerald' },
        { type: 'dict', val: '{"name": "Deepak"}', color: 'purple' },
      ],
    },
  },
  {
    id: 'card-4',
    type: 'code',
    x: 940,
    y: 220,
    width: 270,
    title: 'Control Flow',
    badgeNumber: 4,
    accent: 'orange',
    hasGlow: false,
    data: {
      description: 'Use conditions to make decisions.',
      language: 'python',
      code: `age = 25\nif age >= 18:\n    print("Adult")\nelse:\n    print("Minor")`,
      output: 'Adult',
    },
  },
  {
    id: 'card-diagram',
    type: 'flowchart',
    x: 40,
    y: 470,
    width: 320,
    title: 'Python Flow Diagram',
    accent: 'purple',
    hasGlow: false,
    data: {},
  },
  {
    id: 'card-mindmap',
    type: 'mindmap',
    x: 400,
    y: 530,
    width: 390,
    title: 'Mind Map: Python Topics',
    accent: 'rose',
    hasGlow: true,
    data: {
      center: 'Python',
      topics: [
        { name: 'Variables', color: 'blue' },
        { name: 'Data Types', color: 'emerald' },
        { name: 'Functions', color: 'pink' },
        { name: 'Lists & Dicts', color: 'purple' },
        { name: 'File Handling', color: 'rose' },
        { name: 'Modules', color: 'cyan' },
        { name: 'OOP', color: 'amber' },
        { name: 'Control Flow', color: 'yellow' },
      ],
    },
  },
  {
    id: 'card-5',
    type: 'code',
    x: 910,
    y: 490,
    width: 290,
    title: 'Functions',
    badgeNumber: 5,
    accent: 'purple',
    hasGlow: false,
    data: {
      description: 'Functions help to reuse code.',
      language: 'python',
      code: `def greet(name):\n    return f"Hello, {name}!"\nprint(greet("Deepak"))`,
      output: 'Hello, Deepak!',
    },
  },
  {
    id: 'card-notes',
    type: 'note',
    x: 40,
    y: 770,
    width: 280,
    title: 'Notes',
    accent: 'yellow',
    hasGlow: false,
    data: {
      bullets: [
        'Use meaningful variable names.',
        'Follow PEP 8 style guide.',
        'Practice with small programs.',
        'Build real projects.',
      ],
    },
  },
  {
    id: 'card-concept-img',
    type: 'image_concept',
    x: 350,
    y: 770,
    width: 300,
    title: 'Image / Concept',
    accent: 'purple',
    hasGlow: false,
    data: {
      centerTitle: 'Python',
      modules: [
        { name: 'Web Development', icon: 'globe', color: 'cyan' },
        { name: 'Data Analysis', icon: 'bar-chart', color: 'emerald' },
        { name: 'Automation', icon: 'settings', color: 'amber' },
        { name: 'Machine Learning', icon: 'cpu', color: 'purple' },
      ],
    },
  },
  {
    id: 'card-tasks',
    type: 'tasks',
    x: 680,
    y: 770,
    width: 270,
    title: 'Practice Tasks',
    accent: 'emerald',
    hasGlow: false,
    data: {
      items: [
        { id: 't1', text: 'Create a variable and print it', done: true },
        { id: 't2', text: 'Try different data types', done: false },
        { id: 't3', text: 'Write a simple if-else program', done: false },
        { id: 't4', text: 'Create a function', done: false },
        { id: 't5', text: 'Work with lists', done: false },
        { id: 't6', text: 'Build a small mini project', done: false },
      ],
    },
  },
  {
    id: 'card-resources',
    type: 'resources',
    x: 980,
    y: 770,
    width: 260,
    title: 'Useful Resources',
    accent: 'rose',
    hasGlow: false,
    data: {
      links: [
        { name: 'Python Official Docs', url: 'https://docs.python.org', badge: 'Docs', color: 'blue' },
        { name: 'W3Schools Python', url: 'https://www.w3schools.com/python', badge: 'W', color: 'emerald' },
        { name: 'GeeksforGeeks', url: 'https://www.geeksforgeeks.org/python-programming-language', badge: 'GG', color: 'green' },
        { name: 'Real Python', url: 'https://realpython.com', badge: 'RP', color: 'indigo' },
        { name: 'YouTube Playlist', url: 'https://www.youtube.com', badge: 'YT', color: 'red' },
      ],
    },
  },
];

export const INITIAL_CONNECTIONS: Connection[] = [
  {
    id: 'conn-goal-banner',
    fromId: 'card-goal',
    fromSide: 'left',
    toId: 'card-banner',
    toSide: 'right',
    color: '#f43f5e',
    animated: true,
  },
  {
    id: 'conn-1-diagram',
    fromId: 'card-1',
    fromSide: 'bottom',
    toId: 'card-diagram',
    toSide: 'top',
    color: '#ec4899',
    animated: true,
  },
  {
    id: 'conn-1-2',
    fromId: 'card-1',
    fromSide: 'right',
    toId: 'card-2',
    toSide: 'left',
    color: '#ec4899',
    animated: false,
  },
  {
    id: 'conn-2-3',
    fromId: 'card-2',
    fromSide: 'right',
    toId: 'card-3',
    toSide: 'left',
    color: '#3b82f6',
    animated: false,
  },
  {
    id: 'conn-diagram-2',
    fromId: 'card-diagram',
    fromSide: 'right',
    toId: 'card-2',
    toSide: 'bottom',
    color: '#8b5cf6',
    animated: false,
  },
  {
    id: 'conn-3-mindmap',
    fromId: 'card-3',
    fromSide: 'bottom',
    toId: 'card-mindmap',
    toSide: 'top',
    color: '#10b981',
    animated: true,
  },
  {
    id: 'conn-3-4',
    fromId: 'card-3',
    fromSide: 'right',
    toId: 'card-4',
    toSide: 'left',
    color: '#f97316',
    animated: false,
  },
  {
    id: 'conn-4-5',
    fromId: 'card-4',
    fromSide: 'bottom',
    toId: 'card-5',
    toSide: 'top',
    color: '#ec4899',
    animated: true,
  },
  {
    id: 'conn-5-mindmap',
    fromId: 'card-5',
    fromSide: 'left',
    toId: 'card-mindmap',
    toSide: 'right',
    color: '#3b82f6',
    animated: true,
  },
  {
    id: 'conn-mindmap-tasks',
    fromId: 'card-mindmap',
    fromSide: 'bottom',
    toId: 'card-tasks',
    toSide: 'top',
    color: '#f43f5e',
    animated: true,
  },
  {
    id: 'conn-notes-concept',
    fromId: 'card-notes',
    fromSide: 'right',
    toId: 'card-concept-img',
    toSide: 'left',
    color: '#f59e0b',
    animated: false,
  },
];
