import { ThemeConfig, ThemeId } from '../types/canvas';

export const THEMES: Record<ThemeId, ThemeConfig> = {
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    icon: 'instagram',
    canvasBg: 'bg-[#fafafa]',
    dotsColor: '#e4e4e7',
    cardBg: 'bg-white/95',
    cardBorder: 'border-white/80',
    cardShadow: 'shadow-[0_12px_36px_rgba(236,72,153,0.08),0_4px_12px_rgba(0,0,0,0.04)]',
    primaryGradient: 'from-[#833ab4] via-[#fd1d1d] to-[#fcb045]',
    accentColor: '#e1306c',
    sidebarBg: 'bg-white',
    headerBg: 'bg-white/90',
    textColor: 'text-neutral-800',
    mutedTextColor: 'text-neutral-500',
  },
  apple: {
    id: 'apple',
    name: 'Apple',
    icon: 'apple',
    canvasBg: 'bg-[#f5f5f7]',
    dotsColor: '#d2d2d7',
    cardBg: 'bg-white/90',
    cardBorder: 'border-black/[0.06]',
    cardShadow: 'shadow-[0_8px_30px_rgb(0,0,0,0.06)]',
    primaryGradient: 'from-neutral-800 via-neutral-900 to-black',
    accentColor: '#0071e3',
    sidebarBg: 'bg-[#fbfbfd]',
    headerBg: 'bg-[#fbfbfd]/90',
    textColor: 'text-neutral-900',
    mutedTextColor: 'text-neutral-500',
  },
  nothing: {
    id: 'nothing',
    name: 'Nothing',
    icon: 'nothing',
    canvasBg: 'bg-[#f0f0f2]',
    dotsColor: '#b0b0b8',
    cardBg: 'bg-white/95',
    cardBorder: 'border-neutral-300',
    cardShadow: 'shadow-[0_4px_20px_rgba(0,0,0,0.08)]',
    primaryGradient: 'from-black via-neutral-800 to-neutral-900',
    accentColor: '#d71920',
    sidebarBg: 'bg-white',
    headerBg: 'bg-white/95',
    textColor: 'text-neutral-900',
    mutedTextColor: 'text-neutral-600',
  },
  youtube: {
    id: 'youtube',
    name: 'YouTube',
    icon: 'youtube',
    canvasBg: 'bg-[#f9f9f9]',
    dotsColor: '#e5e5e5',
    cardBg: 'bg-white',
    cardBorder: 'border-neutral-200/80',
    cardShadow: 'shadow-[0_6px_24px_rgba(255,0,0,0.06),0_2px_8px_rgba(0,0,0,0.04)]',
    primaryGradient: 'from-[#ff0000] to-[#cc0000]',
    accentColor: '#ff0000',
    sidebarBg: 'bg-white',
    headerBg: 'bg-white/95',
    textColor: 'text-neutral-900',
    mutedTextColor: 'text-neutral-500',
  },
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    icon: 'facebook',
    canvasBg: 'bg-[#f0f2f5]',
    dotsColor: '#cbd5e1',
    cardBg: 'bg-white',
    cardBorder: 'border-neutral-200',
    cardShadow: 'shadow-[0_6px_24px_rgba(24,119,242,0.08)]',
    primaryGradient: 'from-[#1877f2] to-[#0055d4]',
    accentColor: '#1877f2',
    sidebarBg: 'bg-white',
    headerBg: 'bg-white/95',
    textColor: 'text-neutral-900',
    mutedTextColor: 'text-neutral-500',
  },
  nature: {
    id: 'nature',
    name: 'Nature',
    icon: 'nature',
    canvasBg: 'bg-[#f4f7f4]',
    dotsColor: '#cbd5c0',
    cardBg: 'bg-white/95',
    cardBorder: 'border-emerald-100',
    cardShadow: 'shadow-[0_10px_30px_rgba(16,185,129,0.08)]',
    primaryGradient: 'from-emerald-500 via-teal-500 to-green-600',
    accentColor: '#10b981',
    sidebarBg: 'bg-[#fcfdfc]',
    headerBg: 'bg-[#fcfdfc]/95',
    textColor: 'text-stone-800',
    mutedTextColor: 'text-stone-500',
  },
  dark: {
    id: 'dark',
    name: 'Dark Minimal',
    icon: 'moon',
    canvasBg: 'bg-[#0f1117]',
    dotsColor: '#272b38',
    cardBg: 'bg-[#181c28]/90',
    cardBorder: 'border-white/10',
    cardShadow: 'shadow-[0_14px_40px_rgba(0,0,0,0.6)]',
    primaryGradient: 'from-indigo-500 via-purple-500 to-pink-500',
    accentColor: '#818cf8',
    sidebarBg: 'bg-[#12151f]',
    headerBg: 'bg-[#12151f]/90',
    textColor: 'text-neutral-100',
    mutedTextColor: 'text-neutral-400',
  },
};
